"use client";

import { FormEvent, useEffect, useRef, useState } from "react";
import Link from "next/link";
import { useSearchParams } from "next/navigation";
import { JavaCode } from "@/components/JavaCode";
import { NoteReader } from "@/components/NoteReader";
import { searchLessons } from "@/lib/concepts";
import { cachedAnswer, rememberAnswer, rememberOpenedNote, syncNoteCacheRevision } from "@/lib/opened-notes";

type ProgramChoice = { path: string; title: string; origin: "mongodb" | "github" };

type InterviewResult = {
  source: "repo" | "gemini" | "missing" | "choices";
  origin?: "mongodb" | "github";
  title: string;
  path?: string;
  url?: string;
  code?: string;
  answer?: string;
  focus?: string;
  language?: string;
  note: string;
  choices?: ProgramChoice[];
  related?: ProgramChoice[];
};

const SUGGESTIONS = [
  "Reverse a String",
  "Palindrome Number",
  "Fibonacci Series",
  "Prime Number",
  "Find Duplicate Elements in an Array",
  "Sort an Array",
  "Find the Second Largest Number",
  "Count Character Occurrences",
  "Remove Duplicate Characters",
  "Selenium dropdown handling",
  "Playwright login automation",
  "API testing using REST Assured",
];

function sourceLabel(result: InterviewResult): string {
  if (result.source === "gemini") return "Generated by Gemini";
  if (result.source === "choices") return "Closest programs";
  if (result.origin === "mongodb") return "Found in MongoDB";
  if (result.origin === "github" || result.source === "repo") return "Found in GitHub";
  return "Needs Gemini";
}

export function InterviewDesk() {
  const params = useSearchParams();
  const [question, setQuestion] = useState(params.get("q") || "");
  const [language, setLanguage] = useState("auto");
  const [result, setResult] = useState<InterviewResult | null>(null);
  const [error, setError] = useState("");
  const [notice, setNotice] = useState("");
  const [busy, setBusy] = useState(false);
  const [saving, setSaving] = useState(false);
  const [reading, setReading] = useState(false);
  const [copied, setCopied] = useState(false);
  const answerRef = useRef<HTMLElement>(null);
  const openedQuery = useRef("");

  async function ask(value: string, generate = false) {
    const asked = value.trim();
    if (!asked) {
      setError("Type an interview question.");
      return;
    }
    setBusy(true);
    setError("");
    try {
      try {
        const savedLibrary = window.localStorage.getItem("desk-library-list");
        if (savedLibrary) {
          const revision = (JSON.parse(savedLibrary) as { revision?: string }).revision || "";
          syncNoteCacheRevision(revision);
        }
      } catch {
        // A damaged folder list should not block the interview search.
      }
      const cacheKey = `${language}:${asked}`;
      const cached = generate ? undefined : cachedAnswer(cacheKey);
      if (cached && cached.source !== "choices") {
        setResult(cached);
        setReading(true);
        window.scrollTo(0, 0);
        if (answerRef.current) answerRef.current.scrollTop = 0;
        return;
      }
      const response = await fetch("/api/interview", {
        method: "POST",
        headers: { "Content-Type": "application/json" },
        body: JSON.stringify({ question: asked, language, generate }),
      });
      const data = (await response.json()) as InterviewResult & { error?: string };
      if (!response.ok) throw new Error(data.error || "Could not answer that question.");
      if (data.source !== "choices") rememberAnswer(cacheKey, data);
      if (data.path && data.code) rememberOpenedNote(data.path, "java", data.code);
      if (data.path?.toLowerCase().endsWith(".pdf") && data.answer) rememberOpenedNote(data.path, "pdf", data.answer);
      setResult(data);
      setReading(true);
      window.scrollTo(0, 0);
      if (answerRef.current) answerRef.current.scrollTop = 0;
    } catch (caught) {
      if (!generate) {
        setResult(null);
        setReading(false);
      }
      setError(caught instanceof Error ? caught.message : "Could not answer that question.");
    } finally {
      setBusy(false);
    }
  }

  useEffect(() => {
    if (!reading) return;
    window.scrollTo(0, 0);
    const pane = answerRef.current;
    if (!pane) return;
    const target = pane.querySelector("[data-note-focus]");
    if (!target) {
      pane.scrollTop = 0;
      pane.scrollLeft = 0;
      window.scrollTo(0, 0);
    } else {
      const coverBottom = Math.max(
        pane.querySelector(".note-find")?.getBoundingClientRect().bottom || 0,
        pane.querySelector(".read-bar")?.getBoundingClientRect().bottom || 0,
      );
      const paneScrolls = pane.scrollHeight > pane.clientHeight + 8;
      const anchor = paneScrolls ? pane.getBoundingClientRect().top : 0;
      const delta = target.getBoundingClientRect().top - Math.max(anchor, coverBottom) - 12;
      if (paneScrolls) pane.scrollTop += delta;
      else window.scrollBy(0, delta);
    }
    pane.querySelectorAll(".answer-code").forEach((node) => {
      node.scrollLeft = 0;
    });
  }, [reading, result]);

  useEffect(() => {
    const initial = params.get("q")?.trim() || "";
    if (!initial || openedQuery.current === initial) return;
    openedQuery.current = initial;
    setQuestion(initial);
    void ask(initial);
    // The query is read once when the page opens.
    // eslint-disable-next-line react-hooks/exhaustive-deps
  }, [params]);

  async function openChoice(choice: ProgramChoice) {
    setBusy(true);
    setError("");
    setNotice("");
    try {
      const response = await fetch(`/api/library/file?path=${encodeURIComponent(choice.path)}`);
      const data = (await response.json()) as { text?: string; error?: string };
      if (!response.ok || !data.text) throw new Error(data.error || "Could not open that program.");
      setResult({
        source: "repo",
        origin: choice.origin,
        title: choice.title,
        path: choice.path,
        code: data.text,
        note: choice.origin === "mongodb" ? "Found in MongoDB." : "Found in GitHub.",
      });
      setReading(true);
    } catch (caught) {
      setError(caught instanceof Error ? caught.message : "Could not open that program.");
    } finally {
      setBusy(false);
    }
  }

  async function saveProgram() {
    if (!result || result.source !== "gemini") return;
    setSaving(true);
    setNotice("");
    setError("");
    try {
      const response = await fetch("/api/interview/save", {
        method: "POST",
        headers: { "Content-Type": "application/json" },
        body: JSON.stringify({
          title: question.trim() || result.title,
          language: result.language || language || "java",
          code: result.code || result.answer || "",
          explanation: result.answer || "",
          aliases: [question.trim()],
        }),
      });
      const data = (await response.json()) as { message?: string; error?: string };
      if (!response.ok) throw new Error(data.error || "Could not save that program.");
      setNotice(data.message || "Saved to your library.");
    } catch (caught) {
      setError(caught instanceof Error ? caught.message : "Could not save that program.");
    } finally {
      setSaving(false);
    }
  }

  async function copyCode() {
    const value = result?.code || result?.answer || "";
    if (!value) return;
    try {
      await navigator.clipboard.writeText(value);
      setCopied(true);
      window.setTimeout(() => setCopied(false), 2000);
    } catch {
      setCopied(false);
    }
  }

  function onSubmit(event: FormEvent) {
    event.preventDefault();
    void ask(question);
  }

  return (
    <div className={`interview-page${reading ? " reading" : ""}`}>
      <div className="interview-intro">
        <h1>Interview practice</h1>
        <p className="lede">
          Search a program by name. Desk checks the programs already stored from your GitHub repo, then anything you
          saved. Gemini writes a new explanation only when nothing close is saved.
        </p>
      </div>
      <div className="interview-layout">
      <form className="panel interview-ask" onSubmit={onSubmit}>
        <label htmlFor="interview-question">Program or question</label>
        <textarea
          id="interview-question"
          value={question}
          placeholder="Reverse a String"
          onChange={(event) => setQuestion(event.target.value)}
        />
        <label htmlFor="program-language">Language</label>
        <select id="program-language" value={language} onChange={(event) => setLanguage(event.target.value)}>
          <option value="auto">Match the saved program</option>
          <option value="java">Java</option>
          <option value="javascript">JavaScript</option>
          <option value="typescript">TypeScript</option>
          <option value="python">Python</option>
        </select>
        {error ? <p className="error">{error}</p> : null}
        {notice ? <p className="hint">{notice}</p> : null}
        <div className="actions">
          <button className="btn" type="submit" disabled={busy}>
            {busy ? "Searching programs…" : "Find program"}
          </button>
          {error ? (
            <button className="btn secondary" type="button" disabled={busy} onClick={() => void ask(question)}>
              Retry
            </button>
          ) : null}
        </div>
        <div className="examples">
          {SUGGESTIONS.map((example) => (
            <button
              key={example}
              className="chip"
              type="button"
              onClick={() => {
                setQuestion(example);
                void ask(example);
              }}
            >
              {example}
            </button>
          ))}
        </div>
      </form>
      {result ? (
        <section className="panel answer-panel interview-answer" ref={answerRef}>
          <div className="read-bar">
            <button type="button" onClick={() => setReading(false)}>
              Question
            </button>
            <strong>{result.title}</strong>
          </div>
          <div className="answer-meta">
            <span className={`pill ${result.source === "repo" ? "repo" : "gpt"}`}>{sourceLabel(result)}</span>
            <strong className="read-title">{result.title}</strong>
          </div>
          <p className="hint">{result.note}</p>
          {result.choices?.length ? (
            <div className="examples">
              {result.choices.map((choice) => (
                <button key={choice.path} className="chip" type="button" onClick={() => void openChoice(choice)}>
                  {choice.origin === "mongodb" ? "MongoDB" : "GitHub"}: {choice.title}
                </button>
              ))}
            </div>
          ) : null}
          {result.source === "choices" ? (
            <div className="actions">
              <button className="btn" type="button" disabled={busy} onClick={() => void ask(question, true)}>
                {busy ? "Generating…" : "Generate with Gemini"}
              </button>
            </div>
          ) : null}
          {result.related?.length ? (
            <div className="examples">
              {result.related.map((choice) => (
                <button key={choice.path} className="chip" type="button" onClick={() => void openChoice(choice)}>
                  Related: {choice.title}
                </button>
              ))}
            </div>
          ) : null}
          {searchLessons(question)[0]?.score >= 120 ? (
            <p>
              <Link href={`/concepts?subject=java&topic=${searchLessons(question)[0].id}`} prefetch>
                Open the {searchLessons(question)[0].title} lesson
              </Link>
            </p>
          ) : null}
          {result.url ? (
            <p>
              <a href={result.url} target="_blank" rel="noreferrer">
                {result.path}
              </a>
            </p>
          ) : null}
          {result.code || result.answer ? (
            <div className="actions">
              <button className="btn secondary" type="button" onClick={() => void copyCode()}>
                {copied ? "Copied" : "Copy code"}
              </button>
              {result.source === "gemini" ? (
                <button className="btn" type="button" disabled={saving} onClick={() => void saveProgram()}>
                  {saving ? "Saving…" : "Save to My Library"}
                </button>
              ) : null}
            </div>
          ) : null}
          {result.source === "gemini" && result.answer ? <p className="answer-text">{result.answer}</p> : null}
          {result.source === "gemini" && result.code ? <JavaCode code={result.code} /> : null}
          {result.source !== "gemini" && result.answer && result.code ? <p className="answer-text">{result.answer}</p> : null}
          {result.source !== "gemini" && result.code ? <NoteReader text={result.code} kind="java" title={result.title} /> : null}
          {result.source !== "gemini" && result.answer && !result.code ? (
            <NoteReader text={result.answer} kind="pdf" title={result.title} focus={result.focus} />
          ) : null}
        </section>
      ) : null}
      </div>
    </div>
  );
}
